uint64 serial # serial id of reference poses
uint64 num_reference # Total number of reference poses

float64 dt # Time interval of reference poses

float64[30] x_ref # X reference position in global coordinate
float64[30] y_ref # Y reference position in global coordinate
float64[30] yaw_ref # Yaw angle reference in global coordinate
float64[30] vel_ref # Speed reference
float64[30] acc_ref # Acceleration reference